#!/bin/sh
# ---------------------------------------------------
# Thumbnailer for gif images
#
# Depends on :
#   * gvfs-copy (gvfs-bin package)
#   * convert (imagemagick package)
# Parameters :
#   $1 - URI of office file
#   $2 - full path of generated thumbnail
#   $3 - height of thumbnail in pixels
# ---------------------------------------------------

# check tools availability
command -v gvfs-copy >/dev/null 2>&1 || exit 1
command -v convert >/dev/null 2>&1 || exit 1

# get parameters
FILE_URI=$1
FILE_THUMB=$2
HEIGHT=$3

# get filename extension
FILE_EXT=$(echo "$FILE_URI" | sed 's/^.*\.\(.*\)/\1/')

# generate temporary directory
TMP_DIR=$(mktemp -d)
TMP_BASEFILE="$TMP_DIR/file"

# copy file to temporary local directory
gvfs-copy "${FILE_URI}" "${TMP_BASEFILE}.${FILE_EXT}"

# convert gif to png
convert -thumbnail ${HEIGHT} "${TMP_BASEFILE}.${FILE_EXT}[0]" png:"$FILE_THUMB"

# remove temporary files
rm -R $TMP_DIR
